### ISSUE TITLE
how can I find "SPIN" module ? 

### ISSUE THREAD

**Issue by tky5622** [alexanderbergman7/GNARF#3]
Hi, thank you for your great work!
I tried to run this repository, but I came across this error when I run vizualizer.py
how can I solve this problem?
thank you in advance !

Traceback (most recent call last):
  File "visualizer.py", line 20, in <module>
    from viz import renderer
  File "/mnt/c/Users/takuya/GNARF/viz/renderer.py", line 39, in <module>
    from SPIN import process_EG3D_image
ModuleNotFoundError: No module named 'SPIN'

**Comment by tky5622** [comment]
I think these things are required to run this repository fully.
I'd be glad if we could access to original resources 
thank you for your project!

1. process_EG3D_image
from SPIN import process_EG3D_image

2. xxx_avg.npy
avg_betas="/home/awb/data/SPIN/first2000_meanpose1_factoredrot0/betas_avg.npy",
avg_pose="/home/awb/data/SPIN/first2000_meanpose1_factoredrot0/pose_avg.npy",
avg_global_orient="/home/awb/data/SPIN/first2000_meanpose1_factoredrot0/orient_avg.npy",

**Comment by tky5622** [comment]
SPIN module seems to be this.
https://github.com/nkolot/SPIN

but still, I couldn't find "process_EG3D_image" and "/SPIN/first2000_meanpose1_factoredrot0"
I'd be appreciated it if we could use these files 
thank you in advance !

**Comment by alexanderbergman7** [comment]
Hi,

Currently, the visualizer is untested. I have updated the README in order to reflect this state. It does not support the newer models trained. You can safely comment out process_EG3D_image as it is a method used only for baselines, if you'd like to try the visualizer and see how it runs.

For the *.npy files, it seems like that file is only used in the method `get_reference_mesh`, which is not used anywhere else in the codebase. Can you tell me exactly where this missing file causes the method to fail? I can clean up these extra methods which are not needed. I mainly got the `generate_video` script working on the new SHHQ and higher resolution AIST++ models.
